li_amy_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

from readersclub.views import UserSignup

urlpatterns = [
    path('', include('readersclub.urls')),

    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(
             pattern_name='readersclub_book_list_urlpattern',
             permanent=False
         )),

    path('login/',
         LoginView.as_view(template_name='readersclub/login.html'),
         name='login_urlpattern'
         ),

    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),

    path('signup/', UserSignup,
         name='signup_urlpattern'
         ),

    path('about/', TemplateView.as_view(
            template_name='readersclub/about.html'
         ),
         name='about_urlpattern'),

]

readersclub/urls.py
from django.urls import path
from django.conf.urls import include, url
from readersclub.views import AuthorDetail, AuthorList, BookList, BookDetail, BookCreate, BookUpdate, \
    BookDelete, AuthorCreate, AuthorUpdate, AuthorDelete, ReviewList, ReviewDelete
from . import views

urlpatterns = [
    path('book/',
         BookList.as_view(),
         name='readersclub_book_list_urlpattern'),

    path('book/<int:pk>/',
         BookDetail.as_view(),
         name='readersclub_book_detail_urlpattern'),

    path('book/create/',
         BookCreate.as_view(),
         name='readersclub_book_create_urlpattern'),

    path('book/<int:pk>/update/',
         BookUpdate.as_view(),
         name='readersclub_book_update_urlpattern'),

    path('book/<int:pk>/delete/',
         BookDelete.as_view(),
         name='readersclub_book_delete_urlpattern'),

    path('book/<int:pk>/addreview/',
         views.add_review_to_book,
         name='readersclub_review_create_urlpattern'),

    path('book/<int:pk>/review/',
         ReviewList.as_view(),
         name='readersclub_review_list_urlpattern'),

    path('book/review/<int:pk>/delete/',
         ReviewDelete.as_view(),
         name='readersclub_review_delete_urlpattern'),

    path('book/<int:pk>/vote',
         views.vote,
         name='readers_club_review_vote'),

    path('author/',
         AuthorList.as_view(),
         name='readersclub_author_list_urlpattern'),

    path('author/<int:pk>/',
         AuthorDetail.as_view(),
         name='readersclub_author_detail_urlpattern'
         ),

    path('author/create/',
         AuthorCreate.as_view(),
         name='readersclub_author_create_urlpattern'),

    path('author/<int:pk>/update/',
         AuthorUpdate.as_view(),
         name='readersclub_author_update_urlpattern'),

    path('author/<int:pk>/delete/',
         AuthorDelete.as_view(),
         name='readersclub_author_delete_urlpattern'),

    ]

readersclub/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from django.urls import reverse


class Author(models.Model):
    author_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=200)
    pseudonym = models.CharField(max_length=200, blank=True, default='')
    introduction = models.CharField(max_length=5000)
    awards = models.CharField(max_length=500, blank=True, default='')
    picture_url = models.CharField(max_length=200,
                                   default="../../static/readersclub/harry-potter-clipart-black-and-white-638462-2576998.jpg")

    def __str__(self):
        result = ''
        if self.pseudonym == '':
            return '%s, %s' % (self.last_name, self.first_name)
        else:
            return '%s, %s (%s)' % (self.last_name, self.first_name, self.pseudonym)

    def get_absolute_url(self):
        return reverse('readersclub_author_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('readersclub_author_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('readersclub_author_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name']


class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=500)
    author = models.ForeignKey(Author, related_name='books', on_delete=models.PROTECT)
    introduction = models.CharField(max_length=10000)
    rate = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(10)])
    publisher = models.CharField(max_length=300)
    genre = models.CharField(max_length=200)
    picture_url = models.CharField(max_length=200,
                                   default="../../static/readersclub/logo.png")

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('readersclub_book_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('readersclub_book_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('readersclub_book_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['title']


class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    book = models.ForeignKey(Book, related_name='reviews', on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', related_name='reviews', on_delete=models.CASCADE, blank=True)
    text = models.CharField(max_length=2000)
    rate = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(10)])
    vote = models.IntegerField(default=0)

    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def get_absolute_url(self):
        return reverse('readersclub_review_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('readersclub_review_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return '%s: %s' % (self.author, self.book)

    class Meta:
        ordering = ['review_id']

readersclub/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.http.response import HttpResponse
from django.template import loader
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .utils import PageLinksMixin

from .models import Book, Author, Review
from .forms import ReviewForm, BookForm, AuthorForm


def UserSignup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            group = Group.objects.get(name='rc_user')
            user.groups.add(group)
            return redirect('login_urlpattern')
    else:
        form = UserCreationForm()
    return render(request, 'readersclub/signup.html', {'form': form})


class BookList(PageLinksMixin, ListView):
    template_name = 'readersclub/book_list.html'
    paginate_by = 6
    model = Book

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Book.objects.filter(Q(title__icontains=query) | Q(introduction__icontains=query)
                                       | Q(genre__icontains=query))
        else:
            return Book.objects.all()


# def search_book(request):
#     template_name = 'readersclub/book_list.html'
#     query = request.GET['q']
#     if query:
#         results = Book.objects.filter(Q(title__icontains=query))
#     else:
#         results = Book.objects.all()
#     context = {'results': results}
#
#     return render(request, template_name, context)


class BookDetail(View):
    page_kwarg = 'page'
    paginate_by = 8
    template_name = 'readersclub/book_detail.html'

    def get(self, request, pk):
        book = get_object_or_404(
            Book,
            pk=pk
        )
        review_list = book.reviews.all()

        paginator = Paginator(
            review_list,
            self.paginate_by
        )
        page_number = request.GET.get(
            self.page_kwarg
        )
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(
                paginator.num_pages()
            )
        first_url = "?{pkw}={n}".format(
                pkw=self.page_kwarg,
                n=1
            )
        last_url = "?{pkw}={n}".format(
                pkw=self.page_kwarg,
                n=paginator.num_pages
            )
        if page.has_previous():
            prev_url = "?{pkw}={n}".format(
                pkw=self.page_kwarg,
                n=page.previous_page_number()
            )
        else:
            prev_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(
                pkw=self.page_kwarg,
                n=page.next_page_number()
            )
        else:
            next_url = None
        context = {
            'is_paginated':
                page.has_other_pages(),
            'first_page_url': first_url,
            'last_page_url': last_url,
            'next_page_url': next_url,
            'paginator': paginator,
            'previous_page_url': prev_url,
            'book': book,
            'review_list': page,
        }

        return render(
            request,
            self.template_name,
            context
        )


class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'readersclub.add_book'
    form_class = BookForm
    model = Book


class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'readersclub.change_book'
    form_class = BookForm
    model = Book
    template_name = 'readersclub/book_form_update.html'


class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'readersclub.delete_book'
    model = Book

    def get(self, request, pk):
        book = self.get_object(pk)
        return render(
            request,
            'readersclub/book_confirm_delete.html',
            {'book': book}
        )

    def get_object(self, pk):
        return get_object_or_404(
            Book,
            pk=pk
        )

    def post(self, request, pk):
        book = self.get_object(pk)
        book.delete()
        return redirect('readersclub_book_list_urlpattern')


def add_review_to_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.book = book
            review.author = request.user
            review.published_date = timezone.now()
            review.save()
            return redirect('readersclub_book_detail_urlpattern', pk=book.pk)
    else:
        form = ReviewForm()
    return render(request, 'readersclub/review_form.html', {'form': form})


def vote(request, pk):
    review = get_object_or_404(Review, pk=request.GET.get('rid'))
    if request.GET.get('vote') == 'vote':
        review.vote += 1
        review.save()
    return redirect('readersclub_book_detail_urlpattern', pk=pk)


class ReviewList(LoginRequiredMixin, PermissionRequiredMixin, PageLinksMixin, ListView):
    permission_required = 'readersclub.delete_book'
    template_name = 'readersclub/review_list.html'
    model = Review

    def get_queryset(self):
        query = self.kwargs['pk']
        if query is None:
            return None
        query2 = self.request.GET.get('q')
        reviews = Review.objects.filter(book=query).order_by('-published_date')
        if query2:
            try:
                float(query2)
            except ValueError:
                return reviews.filter(Q(author__username__icontains=query2) |
                                      Q(text__icontains=query2)).order_by('-published_date')
            return reviews.filter(rate__range=(float(query2) - 0.05, float(query2) + 0.05)).order_by('-published_date')
        else:
            return reviews.order_by('-published_date')


class ReviewDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'readersclub.delete_book'
    model = Review

    def get_success_url(self):
        review = get_object_or_404(Review, pk=self.kwargs['pk'])
        book = review.book.book_id
        return reverse_lazy('readersclub_review_list_urlpattern', kwargs={'pk': book})


# class ReviewCreate(CreateView):
#     permission_required = 'readersclub.add_review'
#     form_class = ReviewForm
#     model = Review
#     template_name = 'readersclub/review_form.html'
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         form.instance.book_id = self.kwargs.get['pk']
#         return super(ReviewCreate, self).form_valid(form)
#
#     def get_success_url(self):
#         return redirect(reverse('readersclub_book_detail_urlpattern', kwargs={'pk': self.kwargs.get['pk']}))


class AuthorList(PageLinksMixin, ListView):
    paginate_by = 8
    model = Author

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Author.objects.filter(Q(first_name__icontains=query) |
                                         Q(last_name__icontains=query) |
                                         Q(pseudonym__icontains=query))
        else:
            return Author.objects.all()


class AuthorDetail(View):
    page_kwarg = 'page'
    paginate_by = 20
    template_name = 'readersclub/author_detail.html'

    def get(self, request, pk):
        author = get_object_or_404(
            Author,
            pk=pk
        )
        works = author.books.all()

        paginator = Paginator(
            works,
            self.paginate_by
        )
        page_number = request.GET.get(
            self.page_kwarg
        )
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(
                paginator.num_pages()
            )
        first_url = "?{pkw}={n}".format(
            pkw=self.page_kwarg,
            n=1
        )
        last_url = "?{pkw}={n}".format(
            pkw=self.page_kwarg,
            n=paginator.num_pages
        )
        if page.has_previous():
            prev_url = "?{pkw}={n}".format(
                pkw=self.page_kwarg,
                n=page.previous_page_number()
            )
        else:
            prev_url = None
        if page.has_next():
            next_url = "?{pkw}={n}".format(
                pkw=self.page_kwarg,
                n=page.next_page_number()
            )
        else:
            next_url = None
        context = {
            'is_paginated':
                page.has_other_pages(),
            'first_page_url': first_url,
            'last_page_url': last_url,
            'next_page_url': next_url,
            'paginator': paginator,
            'previous_page_url': prev_url,
            'author': author,
            'works': page,
        }

        return render(
            request,
            self.template_name,
            context
        )


class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):

readersclub/templates/readersclub/about.html
{% extends 'readersclub/base.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
        <h2>About</h2>
        <p>This website provide a platform for book lovers find the information about books and
        share their thoughts with others.</p>
        <p>Users are required to login in if they want to write a review or vote for others' reviews.</p>
        <p>System managers are authorized to edit and add information of books and authors, and manage reviews</p>

        <p>
            For testers: Supervisor(tester: (secret)); User(Chrissy: (secret)), or you can sign up to create a new one.
            Editor(editor1: (secret)).
        </p>
        <p>If you have any questions, or you cannot find your favourite book here, feel free to contact us:
            <br>xxxxx@xxx.com
        </p>
    </div>
  </div>
{% endblock %}

readersclub/templates/readersclub/author_confirm_delete.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Delete Author
{% endblock %}

{% block content %}
    <form
        action="{{ author.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            author {{ author }}?
        </p>
        <a href="{{ author.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Author</button>
    </form>
{% endblock %}

readersclub/templates/readersclub/author_detail.html
{% extends 'readersclub/base.html' %}
{% block title %}
    Author - {{ author }}
{% endblock %}

{% block content %}
    <h2> {{ author }} </h2>
    <ul>
        {% if perms.readersclub.change_author %}
        <a href="{{ author.get_update_url }}"
           class="button">Edit Author</a><br>
        {% endif %}

        {% if perms.readersclub.delete_author %}
        <a href="{{ author.get_delete_url }}"
           class="button">Delete Author</a>
        {% endif %}

    </ul>

    <section>
        <table>
            <tr>
                <td rowspan="6" style="vertical-align: top; padding-right: 20px">
                        <img src="{{ author.picture_url }}" style="height: 150px; width: 110px">
                </td>
            </tr>
            <tr>
                <th>First Name:</th>
                <td>{{ author.first_name }}</td>
            </tr>
            <tr>
                <th>Last Name:</th>
                <td>{{ author.last_name }}</td>
            </tr>
            <tr>
                <th>Pseudonym:</th>
                <td>{{ author.pseudonym }}</td>
            </tr>
            <tr>
                <th>Introduction:</th>
                <td>{{ author.introduction }}</td>
            </tr>
            <tr>
                <th>Awards:</th>
                <td>{{ author.awards }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Works:</h3>
        <ul>
            {% for work in works %}
            <li>
                <a href="{{ work.get_absolute_url }}">{{ work.title }}</a>
            </li>
            {% empty %}
                <li><em>There are currently no work for this author.</em></li>
            {% endfor %}
        </ul>
    </section>
    {% if is_paginated %}
        <div class="row">
            <div class="twelve columns">
                <ul class="pagination">
                    {% if first_page_url %}
                        <li>
                            <a href="{{ first_page_url }}">
                                First</a>
                        </li>
                    {% endif %}
                    {% if previous_page_url %}
                        <li>
                            <a href="{{ previous_page_url }}">
                                Previous</a>
                        </li>
                    {% endif %}
                    <li>
                        Page {{ page_obj.number }}
                        of {{ paginator.num_pages }}
                    </li>
                    {% if next_page_url %}
                        <li>
                            <a href="{{ next_page_url }}">
                                Next</a>
                        </li>
                    {% endif %}
                    {% if last_page_url %}
                        <li>
                            <a href="{{ last_page_url }}">
                                Last</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

readersclub/templates/readersclub/author_list.html
{% extends 'readersclub/base.html' %}

{% block title %}
    Author List
{% endblock %}


{% block content %}

    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        table, th, td {
            border-bottom: 2px solid gainsboro;
            border-top: 2px solid gainsboro;
            vertical-align: middle;
        }

        a {
            text-decoration: none;
        }

        a:hover {text-decoration: underline;}

        tr:hover {
          background-color: lightgrey;
        }

    </style>

    <div class="center">
        <form method="get" action="{% url 'readersclub_author_list_urlpattern' %}">
            <input name="q" placeholder="What are your looking for?" style="height: 35px; width: 200px">
            <button type="submit">SEARCH</button>
        </form>
    </div>

    {% if perms.readersclub.add_author %}
    <a
        href="{% url 'readersclub_author_create_urlpattern'  %}"
        class="button button-primary">
      Add New Author</a>
    {% endif %}

    <h2>Authors</h2>
    <table>
        {% for author in author_list %}
            <tr>
                <td style="text-align: center">
                    <img src="{{ author.picture_url }}"
                     style="height: 50px; width: 50px">
                </td>
                <td>
                    <a href="{{ author.get_absolute_url }}"style="font-size: x-large; color: black;
                    font-family: 'Questrial', sans-serif; padding-right: 20%; padding-bottom: 20px; padding-top: 20px">
                        {{ author }}
                    </a>
                </td>
            </tr>
        {% empty %}
            <li><em>There are currently no author available.</em></li>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <div class="row">
            <div class="twelve columns">
                <ul class="pagination">
                    {% if first_page_url %}
                        <li>
                            <a href="{{ first_page_url }}">
                                First</a>
                        </li>
                    {% endif %}
                    {% if previous_page_url %}
                        <li>
                            <a href="{{ previous_page_url }}">
                                Previous</a>
                        </li>
                    {% endif %}
                    <li>
                        Page {{ page_obj.number }}
                        of {{ paginator.num_pages }}
                    </li>
                    {% if next_page_url %}
                        <li>
                            <a href="{{ next_page_url }}">
                                Next</a>
                        </li>
                    {% endif %}
                    {% if last_page_url %}
                        <li>
                            <a href="{{ last_page_url }}">
                                Last</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

readersclub/templates/readersclub/author_refuse_delete.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Error Deleting Author
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Book</h2>
        <p>
            You may not delete author {{ author }}. This
            author is currently linked with books:
        </p>
            <ul>
                {% for work in works %}
                <li>
                    <a href="{{ work.get_absolute_url }}">{{ work }}</a>
                </li>
                {% endfor %}
            </ul>
        <p>
            Return to <a href="{% url 'readersclub_author_list_urlpattern' %}">Author List</a>
        </p>
    </div>
{% endblock %}

readersclub/templates/readersclub/book_confirm_delete.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Delete Book
{% endblock %}

{% block content %}
    <form
        action="{{ book.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            book {{ book }}?
        </p>
        <a href="{{ book.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Book</button>
    </form>
{% endblock %}

readersclub/templates/readersclub/book_form.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Create Book
{% endblock %}

{% block content %}
    <form
        action="{% url 'readersclub_book_create_urlpattern' %}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Book</button>
    </form>
{% endblock %}

readersclub/templates/readersclub/book_form_update.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Update Book
{% endblock %}

{% block content %}
    <form
        action="{{ book.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Book</button>
    </form>
{% endblock %}

readersclub/templates/readersclub/book_refuse_delete.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Error Deleting Book
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Book</h2>
        <p>
            You may not delete book {{ book }}. This
            book is currently linked with the author:
        </p>
            <ul>
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author }}</a>
                </li>
            </ul>
        <p>
            Return to <a href="{% url 'readersclub_book_list_urlpattern' %}">Book List</a>
        </p>
    </div>
{% endblock %}

readersclub/templates/readersclub/login.html
{% extends 'readersclub/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Login</button>
    </form>

    <p>Do not have an account? Click here to sign up!</p>
    <a href="{% url "signup_urlpattern" %}" class="button button">Sign up</a>
{% endblock %}

readersclub/templates/readersclub/review_detail.html
{% extends 'readersclub/base.html' %}
{% block title %}
    Review
{% endblock %}

{% block content %}
    <section>
        <table>
            <tr>
                <th>Author</th>
                <td>{{ review.author }}</td>
            </tr>
            <tr>
                <th>Text:</th>
                <td>{{ review.text }}</td>
            </tr>
            <tr>
                <th>Rate:</th>
                <td>{{ review.rate }}</td>
            </tr>
        </table>
    </section>
{% endblock %}

readersclub/templates/readersclub/review_form.html
{% extends 'readersclub/base.html' %}

{% block title %}
   Write Review
{% endblock %}

{% block content %}
    <h4>New Review</h4>
    <form id="review" method="post">
        {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Submit Review</button>
    </form>
{% endblock %}

readersclub/templates/readersclub/review_list.html
{% extends 'readersclub/base.html' %}

{% block title %}
    Review List
{% endblock %}

{% block content %}

    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        table, th, td {
            border-bottom: 2px solid gainsboro;
            border-top: 2px solid gainsboro;
            vertical-align: middle;
        }
    </style>

    <div class="center">
        <form method="get">
            <input name="q" placeholder="What are your looking for?" style="height: 35px; width: 200px">
            <button type="submit">SEARCH</button>
        </form>
    </div>

    <h2>Reviews</h2>
    <table>
        <tr>
            <th></th>
            <th>Author:</th>
            <th>Text:</th>
            <th>Rate:</th>
            <th>Vote:</th>
        </tr>
        {% for review in review_list %}
            <tr>
                <td>
                    {% if perms.readersclub.delete_book %}
                        <a href="{{ review.get_delete_url }}"
                        class="button button-primary">Delete Review</a>
                    {% endif %}
                <td>{{ review.author }}</td>
                <td>{{ review.text }}</td>
                <td>{{ review.rate }}</td>
                <td>{{ review.vote }}</td>
            </tr>

        {% empty %}
            <tr><em>There are currently no review available.</em></tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <div class="row">
            <div class="twelve columns">
                <ul class="pagination">
                    {% if first_page_url %}
                        <li>
                            <a href="{{ first_page_url }}">
                                First</a>
                        </li>
                    {% endif %}
                    {% if previous_page_url %}
                        <li>
                            <a href="{{ previous_page_url }}">
                                Previous</a>
                        </li>
                    {% endif %}
                    <li>
                        Page {{ page_obj.number }}
                        of {{ paginator.num_pages }}
                    </li>
                    {% if next_page_url %}
                        <li>
                            <a href="{{ next_page_url }}">
                                Next</a>
                        </li>
                    {% endif %}
                    {% if last_page_url %}
                        <li>
                            <a href="{{ last_page_url }}">
                                Last</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}